@startmindmap
skinparam monochrome false

* <color:orange> ☐ Focus
** ☐ I18n

* <color:red> ☐ Bugs
** ☐ NPE bei geänderten Klassennamen oder -package
** ☐ ignores package names with Uppercase

* <color:blue> ☐ ToDos
** ☐ Renderer wiederverwenden
** ☐ Tests
** ☐ Publish nach MavenLocal
** ☐ Publish nach Intellij Market
** ☐ Default-Options-Panel
** ☐ Weitere Optionen
*** ☐ Default-Block in Diagram
*** ☐ auto render
*** ☐ auto compile
*** ☐ show containers
*** ☐ Marker interfaces
*** ☐ Colors for Marker interfaces
** ☑ selber Rendern statt via PlantUml-Plugin
*** ☑ Copy to Clipboard
*** ☐ Maximal Breite erweitern


* <color:green> ☑ Features\n <color:green> implemented
** ☑ Analyse komp. Klassen
** ☑ Diagram in Editor öffnen
** ☑ gegebene Parameter im Diagramm
** ☑ weitere Klassen hinzufügen, ausblenden
** ☑ Wenn Diagramm im Focus, Parameter aus Diagramm lesen
** ☑ Konfigurationspanel
** ☑ Alle Parameter ins Params-Objekt
** ☑ workingDirs for Multimoduleprojekte
** ☑ Class<<data>> in gefundene Klassen
** ☑ ToolWindow mit Diagramm
** ☑ Weitere Optionen
*** ☑ Tree für Klassen-Selektion

@endmindmap
