@startmindmap
skinparam monochrome false

* <color:orange> ☐ Focus

* <color:red> ☐ Bugs

* <color:blue> ☐ ToDos
** ☐ I18n
** ☐ dropdown with presets
** ☐ Context Menu: Focus in new Diagram (fast)
** ☐ Publish nach Intellij Market
** ☐ Weitere Optionen


* <color:green> ☑ Features\n <color:green> implemented
** ☑ Analyse komp. Klassen
** ☑ Diagram in Editor öffnen
** ☑ gegebene Parameter im Diagramm
** ☑ weitere Klassen hinzufügen, ausblenden
** ☑ Wenn Diagramm im Focus, Parameter aus Diagramm lesen
** ☑ Konfigurationspanel
** ☑ Alle Parameter ins Params-Objekt
** ☑ workingDirs for Multimoduleprojekte
** ☑ Class<<data>> in gefundene Klassen
** ☑ ToolWindow mit Diagramm
** ☑ Tests
** ☑ selber Rendern statt via PlantUml-Plugin
*** ☑ Copy to Clipboard
*** ☑ Maximal Breite erweitern
** ☑ Weitere Optionen
*** ☑ Tree für Klassen-Selektion
*** ☑ Default-Block in Diagram
*** ☑ auto render
*** ☑ Marker interfaces
*** ☑ Colors for Marker interfaces
*** ☑ run compile
*** ☑ show containers
** ☑ Renderer wiederverwenden
** ☑ Default-Options-Panel
** ☑ SVG
** ☑ Bugfixes
*** ☑ ignores package names with Uppercase
** ☑ Hide Options


@endmindmap
